// GENERATED by scripts/sg-region/build.mjs. Do not edit by hand.
// Weekly slugs (M-D-YY) per unlisted region, oldest → newest. The Worker redirects
// bare region URLs to the last one.
export const REGION_WEEKS = {
  "/SGchurch/MidwestNorthwest": [
    "9-27-26"
  ],
  "/SGchurch/SovereignGrace": [
    "9-27-26"
  ]
};
